export const ocos = [
    { value: '00', key: '00', text: 'Processo de Transporte já Iniciado' },
    { value: '01', key: '01', text: 'Entrega Realizada Normalmente' },
    { value: '02', key: '02', text: 'Entrega Fora da Data Programada' },
    { value: '03', key: '03', text: 'Recusa por Falta de Pedido de Compra' },
    { value: '04', key: '04', text: 'Recusa por Pedido de Compra Cancelado' },
    {
        value: '05',
        key: '05',
        text: 'Falta de Espaço Físico no Depósito do Cliente Destino',
    },
    {
        value: '06',
        key: '06',
        text: 'Endereço do Cliente Destino não Localizado',
    },
    { value: '07', key: '07', text: 'Devolução não Autorizada pelo Cliente' },
    {
        value: '08',
        key: '08',
        text: 'Preço Mercadoria em Desacordo com o Pedido de Compra',
    },
    {
        value: '09',
        key: '09',
        text: 'Mercadoria em Descordo com o Pedido de Compra',
    },
    {
        value: '10',
        key: '10',
        text: 'Cliente Destino somente Recebe Mercadoria com Frete Pago',
    },
    {
        value: '11',
        key: '11',
        text: 'Recusa por Deficiência Embalagem Mercadoria',
    },
    { value: '12', key: '12', text: 'Redespacho não Indicado' },
    {
        value: '13',
        key: '13',
        text: 'Transportadora não Atende a Cidade do Cliente Destino',
    },
    { value: '14', key: '14', text: 'Mercadoria Sinistrada' },
    { value: '15', key: '15', text: 'Embalagem Sinistrada' },
    { value: '16', key: '16', text: 'Pedido de Compras em Duplicidade' },
    {
        value: '17',
        key: '17',
        text: 'Mercadoria fora da Embalagem de Atacadista',
    },
    { value: '18', key: '18', text: 'Mercadorias Trocadas' },
    { value: '19', key: '19', text: 'Reentrega Solicitada pelo Cliente' },
    {
        value: '20',
        key: '20',
        text: 'Entrega Prejudicada por Horário/Falta de Tempo Hábil',
    },
    { value: '21', key: '21', text: 'Estabelecimento Fechado' },
    { value: '22', key: '22', text: 'Reentrega sem Cobrança do Cliente' },
    { value: '23', key: '23', text: 'Extravio de Mercadoria em Trânsito' },
    {
        value: '24',
        key: '24',
        text: 'Mercadoria Reentregue ao Cliente Destino',
    },
    {
        value: '25',
        key: '25',
        text: 'Mercadoria Devolvida ao Cliente de Origem',
    },
    { value: '26', key: '26', text: 'Nota Fiscal Retida pela Fiscalização' },
    { value: '27', key: '27', text: 'Roubo de Carga' },
    { value: '28', key: '28', text: 'Mercadoria Retida até Segunda Ordem' },
    {
        value: '29',
        key: '29',
        text: 'Cliente Retira Mercadoria na Transportadora',
    },
    {
        value: '30',
        key: '30',
        text: 'Problema com a Documentação (Nota Fiscal e/ou CTRC)',
    },
    { value: '31', key: '31', text: 'Entrega com Indenização Efetuada' },
    { value: '32', key: '32', text: 'Falta com Solicitação de Reposição' },
    { value: '33', key: '33', text: 'Falta com Busca/Reconferência' },
    { value: '34', key: '34', text: 'Cliente Fechado para Balanço' },
    {
        value: '35',
        key: '35',
        text: 'Quantidade de Produto em Desacordo (Nota Fiscal e/ou Pedido)',
    },
    { value: '36', key: '36', text: 'Extravio de documentos pela cia. Aérea ' },
    { value: '37', key: '37', text: 'Extravio de carga pela cia. Aérea ' },
    { value: '38', key: '38', text: 'Avaria de carga pela cia. Aérea ' },
    { value: '39', key: '39', text: 'Corte de carga na pista ' },
    { value: '40', key: '40', text: 'Aeroporto fechado na origem ' },
    { value: '41', key: '41', text: 'Pedido de Compra Incompleto' },
    {
        value: '42',
        key: '42',
        text: 'Nota Fiscal com Produtos de Setores Diferentes',
    },
    { value: '43', key: '43', text: 'Feriado Local/Nacional' },
    { value: '44', key: '44', text: 'Excesso de Veículos' },
    { value: '45', key: '45', text: 'Cliente Destino Encerrou Atividades' },
    { value: '46', key: '46', text: 'Responsável de Recebimento Ausente' },
    { value: '47', key: '47', text: 'Cliente Destino em Greve' },
    { value: '48', key: '48', text: 'Aeroporto fechado no destino ' },
    { value: '49', key: '49', text: 'Vôo Cancelado ' },
    { value: '50', key: '50', text: 'Greve nacional (Greve Geral)' },
    {
        value: '51',
        key: '51',
        text: 'Mercadoria Vencida (Data de Validade Expirada)',
    },
    {
        value: '52',
        key: '52',
        text: 'Mercadoria Redespachada (Entregue para Redespacho)',
    },
    {
        value: '53',
        key: '53',
        text: 'Mercadoria não foi Embarcada, Permanecendo na Origem',
    },
    {
        value: '54',
        key: '54',
        text: 'Mercadoria Embarcada sem Conhecimento/Conhecimento não Embarcado',
    },
    {
        value: '55',
        key: '55',
        text: 'Endereço de Transportadora de Redespacho não Localizado/Informado',
    },
    {
        value: '56',
        key: '56',
        text: 'Cliente não Aceita Mercadoria com Pagamento de Reembolso',
    },
    {
        value: '57',
        key: '57',
        text: 'Transportadora não Atende a Cidade da Transportadora de Redespacho',
    },
    { value: '58', key: '58', text: 'Quebra do Veículo de Entrega' },
    { value: '59', key: '59', text: 'Cliente sem Verba para Pagar o Frete' },
    { value: '60', key: '60', text: 'Endereço de Entrega Errado' },
    { value: '61', key: '61', text: 'Cliente sem Verba para Reembolso' },
    {
        value: '62',
        key: '62',
        text: 'Recusa da Carga por Valor de Frete Errado',
    },
    {
        value: '63',
        key: '63',
        text: 'Identificação do Cliente não Informada/Enviada/Insuficiente',
    },
    { value: '64', key: '64', text: 'Cliente não Identificado/Cadastrado' },
    { value: '65', key: '65', text: 'Entrar em Contato com o Comprador' },
    { value: '66', key: '66', text: 'Troca não Disponível' },
    { value: '67', key: '67', text: 'Fins Estatísticos' },
    { value: '68', key: '68', text: 'Data de Entrega Diferente do Pedido' },
    { value: '69', key: '69', text: 'Substituição Tributária' },
    { value: '70', key: '70', text: 'Sistema Fora do Ar' },
    {
        value: '71',
        key: '71',
        text: 'Cliente Destino não Recebe Pedido Parcial',
    },
    {
        value: '72',
        key: '72',
        text: 'Cliente Destino só Recebe Pedido Parcial',
    },
    { value: '73', key: '73', text: 'Redespacho somente com Frete Pago' },
    {
        value: '74',
        key: '74',
        text: 'Funcionário não autorizado a Receber Mercadorias',
    },
    { value: '75', key: '75', text: 'Mercadoria Embarcada para Rota Indevida' },
    { value: '76', key: '76', text: 'Estrada/Entrada de Acesso Interditada' },
    { value: '77', key: '77', text: 'Cliente Destino Mudou de Endereço' },
    { value: '78', key: '78', text: 'Avaria Total' },
    { value: '79', key: '79', text: 'Avaria Parcial' },
    { value: '80', key: '80', text: 'Extravio Total' },
    { value: '81', key: '81', text: 'Extravio Parcial' },
    { value: '82', key: '82', text: 'Sobra de Mercadoria sem Nota Fiscal' },
    {
        value: '83',
        key: '83',
        text: 'Mercadoria em poder da SUFRAMA para Internação',
    },
    { value: '84', key: '84', text: 'Mercadoria Retirada para Conferência' },
    { value: '85', key: '85', text: 'Apreensão Fiscal da Mercadoria' },
    { value: '86', key: '86', text: 'Excesso de Carga/Peso' },
    { value: '87', key: '87', text: 'Férias Coletivas' },
    { value: '88', key: '88', text: 'Recusado, aguardando negociação' },
    {
        value: '89',
        key: '89',
        text: 'Aguardando refaturamento das mercadorias',
    },
    { value: '90', key: '90', text: 'Recusado pelo Redespachante' },
    { value: '91', key: '91', text: 'Entrega Programada' },
    { value: '92', key: '92', text: 'Problemas Fiscais' },
    { value: '93', key: '93', text: 'Aguardando carta de correção' },
    {
        value: '94',
        key: '94',
        text: 'Recusa por divergência nas condições de pagamento',
    },
    { value: '95', key: '95', text: 'Carga aguardando voo conexão ' },
    {
        value: '96',
        key: '96',
        text: 'Carga sem embalagem própria para transp. Aéreo ',
    },
    {
        value: '97',
        key: '97',
        text: 'Carga com dimensão superior ao porão da aeronave ',
    },
    { value: '98', key: '98', text: 'Chegada na cidade ou filial de destino' },
    {
        value: '99',
        key: '99',
        text: 'Outros tipos de ocorrências não especificados acima',
    },
].map(oco => ({ ...oco, text: `${oco.value} - ${oco.text}` }));
